spark_dbt:
  outputs:
    dev:
      dbname: '{{ env_var(''DBT_DB'') }}'
      host: '{{ env_var(''DBT_HOST'') }}'
      pass: '{{ env_var(''DBT_PASSWORD'') }}'
      port: 5439
      schema: '{{ env_var(''DBT_SCHEMA'') }}'
      threads: 4
      type: redshift
      user: '{{ env_var(''DBT_USER'') }}'
  target: dev
spark_parquet:
  outputs:
    dev:
      host: spark-thrift
      method: thrift
      port: 10000
      schema: default
      threads: 1
      type: spark
  target: dev
